# Local database setup
login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development:
  database: refinerycms-website
  <<: *login

test:
  database: refinerycms-website
  <<: *login
