login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: refinerycms_website
  <<: *login

test: &test
  database: refinerycms_website_test
  <<: *login

production: &production
  adapter: mysql2
  host: localhost
  database: your_production_database
  username: your_production_database_login
  password: your_production_database_password
